"""Add roles, directories, and separate participants

Revision ID: a05f740643a9
Revises: abb71d447b3e
Create Date: 2025-11-26 16:43:20.426764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a05f740643a9'
down_revision: Union[str, Sequence[str], None] = 'abb71d447b3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('directories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_directories_id'), 'directories', ['id'], unique=False)
    op.create_index(op.f('ix_directories_name'), 'directories', ['name'], unique=True)
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('event_date', sa.DateTime(), nullable=True),
    sa.Column('registration_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.create_index(op.f('ix_events_title'), 'events', ['title'], unique=False)
    op.create_table('participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('full_name', 'note', name='uc_full_name_note')
    )
    op.create_index(op.f('ix_participants_email'), 'participants', ['email'], unique=True)
    op.create_index(op.f('ix_participants_full_name'), 'participants', ['full_name'], unique=False)
    op.create_index(op.f('ix_participants_id'), 'participants', ['id'], unique=False)
    op.create_table('system_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'REGISTRAR', name='systemuserrole'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_users_id'), 'system_users', ['id'], unique=False)
    op.create_index(op.f('ix_system_users_username'), 'system_users', ['username'], unique=True)
    op.create_table('directory_memberships',
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('directory_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['directory_id'], ['directories.id'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.PrimaryKeyConstraint('participant_id', 'directory_id')
    )
    op.create_table('registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('participant_id', sa.Integer(), nullable=True),
    sa.Column('registered_by_user_id', sa.Integer(), nullable=False),
    sa.Column('registration_time', sa.DateTime(), nullable=True),
    sa.Column('arrival_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.ForeignKeyConstraint(['registered_by_user_id'], ['system_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'participant_id', name='uc_event_participant')
    )
    op.create_index(op.f('ix_registrations_event_id'), 'registrations', ['event_id'], unique=False)
    op.create_index(op.f('ix_registrations_id'), 'registrations', ['id'], unique=False)
    op.create_index(op.f('ix_registrations_participant_id'), 'registrations', ['participant_id'], unique=False)
    op.create_index(op.f('ix_registrations_registered_by_user_id'), 'registrations', ['registered_by_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_registrations_registered_by_user_id'), table_name='registrations')
    op.drop_index(op.f('ix_registrations_participant_id'), table_name='registrations')
    op.drop_index(op.f('ix_registrations_id'), table_name='registrations')
    op.drop_index(op.f('ix_registrations_event_id'), table_name='registrations')
    op.drop_table('registrations')
    op.drop_table('directory_memberships')
    op.drop_index(op.f('ix_system_users_username'), table_name='system_users')
    op.drop_index(op.f('ix_system_users_id'), table_name='system_users')
    op.drop_table('system_users')
    op.drop_index(op.f('ix_participants_id'), table_name='participants')
    op.drop_index(op.f('ix_participants_full_name'), table_name='participants')
    op.drop_index(op.f('ix_participants_email'), table_name='participants')
    op.drop_table('participants')
    op.drop_index(op.f('ix_events_title'), table_name='events')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_directories_name'), table_name='directories')
    op.drop_index(op.f('ix_directories_id'), table_name='directories')
    op.drop_table('directories')
    # ### end Alembic commands ###
